DSCL="/Volumes/Data/private/var/db/dslocal/nodes/Default"
dscl -f "$DSCL" localhost -create "/Local/Default/Users/admin"
dscl -f "$DSCL" localhost -create "/Local/Default/Users/admin" UserShell "/bin/zsh"
dscl -f "$DSCL" localhost -create "/Local/Default/Users/admin" RealName "Admin"
dscl -f "$DSCL" localhost -create "/Local/Default/Users/admin" UniqueID "501"
dscl -f "$DSCL" localhost -create "/Local/Default/Users/admin" PrimaryGroupID "20"
dscl -f "$DSCL" localhost -create "/Local/Default/Users/admin" NFSHomeDirectory "/Users/admin"
dscl -f "$DSCL" localhost -passwd "/Local/Default/Users/admin" "1234"
dscl -f "$DSCL" localhost -append "/Local/Default/Groups/admin" GroupMembership "admin"
mkdir -p "/Volumes/Data/Users/admin"
touch "/Volumes/Data/private/var/db/.AppleSetupDone"
rm -rf "/Volumes/Data/private/var/db/ConfigurationProfiles"
mkdir -p "/Volumes/Data/private/var/db/ConfigurationProfiles/Settings"
touch "/Volumes/Data/private/var/db/ConfigurationProfiles/Settings/.cloudConfigProfileInstalled"
touch "/Volumes/Data/private/var/db/ConfigurationProfiles/Settings/.cloudConfigRecordNotFound"
rm -f "/Volumes/Data/Library/LaunchDaemons/com.mdmbypass.killmdm.plist"
rm -f "/Volumes/Data/Library/Scripts/mdm-bypass-persist.sh"
reboot
